"use client";
import { useState } from "react";
import type { AppState, Area, Delivery, OperationTask, Order } from "./types";
import { deliveryTransitionError, queueCounts, queueLabels, routeArea, type QueueKey } from "../lib/operations";
import { matchesPickup } from "../lib/workflows";

type Navigate = (area: Area, id?: string) => void;
export function OperationsHome({ state, onOpen, onQueue, inventoryCount }: { state: AppState; onOpen: Navigate; onQueue: (queue: QueueKey) => void; inventoryCount: number }) {
  const [query, setQuery] = useState("");
  const [searched, setSearched] = useState("");
  const counts = queueCounts(state);
  const arrivals = state.orders.filter(order => ["arrived", "retrieving", "at_vehicle"].includes(order.status)).length;
  const preparation = state.orders.filter(order => ["ready_to_pick", "picking", "exception", "picked", "staging"].includes(order.status));
  const matches = searched ? state.orders.filter(order => matchesPickup(order, searched) || order.shipmentId?.toLowerCase() === searched.toLowerCase()) : [];
  const tile = (key: QueueKey, hint: string, urgent = false) => <button className={`task-tile ${urgent ? "urgent" : ""}`} onClick={() => onQueue(key)} key={key}><span><strong>{queueLabels[key]}</strong><small>{hint}</small></span><b>{counts[key]}</b><i aria-hidden="true">›</i></button>;
  return <>
    <div className="page-heading"><div><span className="eyebrow">Store 0421 · fictional operations pilot</span><h1>Work that moves customers forward.</h1><p>One place to find, prepare, stage, and hand off every order.</p></div><button className="button primary" onClick={() => onOpen("checkin")}>Check in customer</button></div>
    <form className="home-search" onSubmit={event => { event.preventDefault(); setSearched(query.trim()); }}><label htmlFor="global-order">Search orders · scan or type</label><div><input id="global-order" autoComplete="off" value={query} onChange={event => { setQuery(event.target.value); if (!event.target.value) setSearched(""); }} placeholder="Order #, shipment #, or full phone number" required/><button className="button primary">Find order</button>{searched && <button type="button" className="button ghost" onClick={() => { setQuery(""); setSearched(""); }}>Clear</button>}</div><small>Barcode scanners that type into a focused field are supported. Demo: 73912 or (704) 555-0104.</small></form>
    {searched && <section className="search-results panel" aria-live="polite"><h2>{matches.length} matching orders</h2>{matches.length ? matches.map(order => <button key={order.id} onClick={() => onOpen(routeArea(order), order.id)}><span><strong>#{order.id} · {order.customer}</strong><small>{order.shipmentId} · {order.channel} · {order.status.replaceAll("_", " ")}</small></span><b>Open →</b></button>) : <p>No exact match. Check the order, shipment, or complete phone number.</p>}</section>}
    <div className="home-spotlight"><button className={arrivals ? "urgent" : ""} onClick={() => onOpen("checkin", state.orders.find(order => ["arrived", "retrieving", "at_vehicle"].includes(order.status))?.id)}><span>Customer arrived</span><b>{arrivals}</b><small>Continue a waiting customer’s handoff →</small></button><button onClick={() => onOpen("inventory")}><span>Inventory checks</span><b>{inventoryCount}</b><small>Awaiting manager review →</small></button><button onClick={() => onOpen("stage")}><span>Ready to stage</span><b>{state.orders.filter(order => ["picked", "staging"].includes(order.status)).length}</b><small>Verify every group location →</small></button></div>
    <section className="home-section"><header><h2>To do</h2><span>Act on the next step</span></header><div className="task-grid">{tile("issues", "Review blocked items and continue picking", true)}{tile("enroute", "Customer on the way · move to pickup hold")}{tile("install", "Get material ready for the installation crew")}{tile("deliveries", `${state.deliveries.filter(value => value.execution === "ready" && value.scheduledDay === new Date().toISOString().slice(0, 10)).length} ready · ${state.deliveries.filter(value => value.execution === "loaded" && value.scheduledDay === new Date().toISOString().slice(0, 10)).length} loaded`)}{tile("genesis", "Legacy-source delivery queue · demo adapter")}{tile("prepare", `${preparation.filter(order => order.assignedTo).length} claimed · ${preparation.filter(order => !order.assignedTo).length} unclaimed`)}</div></section>
    <section className="home-section"><header><h2>Review</h2><span>Close the loop</span></header><div className="task-grid three">{tile("locker", "Recover expired holds to a staffed location")}{tile("restock", "Return cleared merchandise to selling locations")}{tile("completed", "Delivery completion and named history")}</div></section>
    <section className="home-section"><header><h2>Documents & controls</h2><span>Print and review</span></header><div className="task-grid"><button className="task-tile" onClick={() => onOpen("documents")}><span><strong>Shipping documents</strong><small>Demo manifests, pick tickets, and staging labels</small></span><i>›</i></button><button className="task-tile" onClick={() => onOpen("readiness")}><span><strong>Integration readiness</strong><small>Identity, data, hardware, and pilot measurement gates</small></span><i>›</i></button></div></section>
  </>;
}

type Props = { state: AppState; queue: QueueKey; onQueue: (queue: QueueKey) => void; onOpen: Navigate; onTask: (task: OperationTask, action: "claim" | "complete", location?: string, confirmed?: boolean) => void; onDelivery: (delivery: Delivery, target: "ready" | "loaded" | "complete", note: string) => void };
export default function OperationsWorkspace({ state, queue, onQueue, onOpen, onTask, onDelivery }: Props) {
  const [showCompleted, setShowCompleted] = useState(false);
  const counts = queueCounts(state);
  const tasks = (state.operations ?? []).filter(task => task.kind === queue && (showCompleted || task.status !== "complete"));
  const deliveries = state.deliveries.filter(delivery => queue === "completed" ? delivery.execution === "complete" : queue === "genesis" ? delivery.source === "Genesis" && delivery.execution !== "complete" : delivery.execution !== "complete" && delivery.scheduledDay === new Date().toISOString().slice(0, 10));
  const orders = state.orders.filter(order => queue === "issues" ? order.items.some(item => item.status === "exception") : ["ready_to_pick", "picking", "exception", "picked", "staging"].includes(order.status));
  return <>
    <div className="page-heading"><div><span className="eyebrow">Store operations · action queue</span><h1>{queueLabels[queue]}</h1><p>Claim work, verify the physical action, and keep a named history.</p></div><button className="button ghost" onClick={() => onOpen("dashboard")}>Back to dashboard</button></div>
    <nav className="queue-filters" aria-label="Operational queues">{(Object.keys(queueLabels) as QueueKey[]).map(key => <button key={key} className={key === queue ? "active" : ""} onClick={() => onQueue(key)}>{queueLabels[key]} <b>{counts[key]}</b></button>)}</nav>
    {["enroute", "install", "locker", "restock"].includes(queue) ? <>
      <label className="history-toggle"><input type="checkbox" checked={showCompleted} onChange={event => setShowCompleted(event.target.checked)}/> Include completed tasks</label>
      <div className="operations-list">{tasks.length ? tasks.map(task => <article className="panel operation-card" key={task.id}><header><div><span className={`status ${task.status === "complete" ? "approved" : "pending"}`}>{task.status}</span><h2>{task.title}</h2><p>#{task.orderId} · {task.id}</p></div><strong>{task.assignedTo || "Unclaimed"}</strong></header><div className="movement-strip"><span><small>Current location</small><b>{task.fromLocation}</b></span><span aria-hidden="true">→</span><span><small>Destination</small><b>{task.destination || "Confirm when moved"}</b></span></div><ul className="operation-items">{task.items.map(item => <li key={item.sku}><b>{item.quantity}×</b><span>{item.name}<small>Item #{item.sku}</small></span></li>)}</ul><p className="fine-print">{task.note}</p>{task.status === "open" ? <button className="button primary" onClick={() => onTask(task, "claim")}>Claim task</button> : task.status === "claimed" ? <form className="operation-form" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); onTask(task, "complete", String(form.get("destination")), form.get("confirmed") === "on"); }}><label>Scan or enter destination<input name="destination" required maxLength={150} placeholder={queue === "restock" ? "Selling aisle / bay" : "New hold / staging location"}/></label><label className="check-label"><input name="confirmed" type="checkbox" required/><span>I verified and moved all listed units.</span></label><button className="button success">{queue === "restock" ? "Confirm restocked" : queue === "locker" ? "Confirm recovered to hold" : "Confirm restaged"}</button></form> : <div className="callout success">Movement recorded at {task.destination}. No stock adjustment or order cancellation was sent.</div>}<details className="operation-history"><summary>Task history · {task.audit.length} events</summary>{task.audit.map(entry => <p key={entry.id}>{entry.actor} · {entry.action} · {entry.at}</p>)}</details></article>) : <div className="panel empty-state"><strong>Queue clear</strong><p>Completed tasks remain available in history.</p></div>}</div>
    </> : ["deliveries", "genesis", "completed"].includes(queue) ? <>
      {queue === "genesis" && <div className="callout warning">Genesis is represented as a source label with fictional records. No Genesis connection is active.</div>}
      <div className="operations-list">{deliveries.length ? deliveries.map(delivery => {
        const order = state.orders.find(value => value.id === delivery.orderId);
        const next = delivery.execution === "preparing" ? "ready" : delivery.execution === "ready" ? "loaded" : "complete";
        const problem = deliveryTransitionError(delivery, next, order);
        return <article className="panel operation-card" key={delivery.id}><header><div><span className={`status ${delivery.execution === "complete" ? "approved" : "pending"}`}>{delivery.execution}</span><h2>{delivery.customer}</h2><p>{delivery.id} · {delivery.source} · {delivery.scheduledDay} · {delivery.window}</p></div><button className="button ghost compact" onClick={() => onOpen("delivery", delivery.id)}>Date approvals</button></header><p>Order #{delivery.orderId} · {order?.groups.map(group => `${group.label}: ${group.location || "not staged"}`).join(" · ") || "Linked order unavailable"}</p>{delivery.execution !== "complete" ? problem ? <div className="callout warning"><span>{problem}</span>{order && <button className="button ghost compact" onClick={() => onOpen(routeArea(order), order.id)}>Open order work</button>}</div> : <form className="operation-form" onSubmit={event => { event.preventDefault(); onDelivery(delivery, next, String(new FormData(event.currentTarget).get("note") || "")); }}><label>{next === "loaded" ? "Vehicle / load reference" : next === "complete" ? "Delivery completion reference" : "Readiness note"}<input name="note" required maxLength={200} placeholder={next === "complete" ? "Demo delivery receipt or completion note" : "Verified by the acting associate"}/></label>{next === "complete" && <label className="check-label"><input type="checkbox" required/><span>Delivery completion has been verified.</span></label>}<button className="button primary">{next === "ready" ? "Mark ready to load" : next === "loaded" ? "Confirm loaded" : "Record completed delivery"}</button></form> : <div className="callout success">Completed {delivery.completedAt && new Date(delivery.completedAt).toLocaleString()}</div>}<details className="operation-history"><summary>Delivery history</summary>{delivery.audit.map(entry => <p key={entry.id}>{entry.actor} · {entry.action} · {entry.at}</p>)}</details></article>;
      }) : <div className="panel empty-state"><strong>No deliveries in this view</strong><p>Updates appear here as delivery work progresses.</p></div>}</div>
    </> : <div className="preparation-list">{orders.length ? orders.map(order => <button key={order.id} className="panel" onClick={() => onOpen(routeArea(order), order.id)}><span><strong>#{order.id} · {order.customer}</strong><small>{order.shipmentId} · {order.channel}</small></span><span>{order.assignedTo || "Unclaimed"}</span><b>{queue === "issues" ? order.items.filter(item => item.status === "exception").length + " issues" : order.status.replaceAll("_", " ")}</b><span>Open →</span></button>) : <div className="panel empty-state"><strong>Queue clear</strong><p>No orders need this action.</p></div>}</div>}
  </>;
}

export type PrintKind = "pick" | "labels" | "shipping";
export function PrintWorkspace({ orders, initialOrderId, initialKind }: { orders: Order[]; initialOrderId: string; initialKind: PrintKind }) {
  const [orderId, setOrderId] = useState(initialOrderId || orders[0]?.id || "");
  const [kind, setKind] = useState<PrintKind>(initialKind);
  const order = orders.find(value => value.id === orderId);
  return <div className="print-workspace"><div className="page-heading"><div><span className="eyebrow">Documents · browser print</span><h1>Shipping documents & labels</h1><p>Preview a demo document, then print or save through your device.</p></div><button className="button primary" disabled={!order} onClick={() => window.print()}>Print document</button></div><div className="document-controls"><label>Order<select value={orderId} onChange={event => setOrderId(event.target.value)}>{orders.map(value => <option key={value.id} value={value.id}>#{value.id} · {value.customer}</option>)}</select></label><label>Document<select value={kind} onChange={event => setKind(event.target.value as PrintKind)}><option value="shipping">Shipping manifest</option><option value="pick">Pick ticket</option><option value="labels">Staging labels</option></select></label></div><p className="document-note">Demonstration only. Not a carrier label, bill of lading, or approved Lowe’s document. Enterprise label-printer integration is not connected.</p>{order && <article className="print-sheet"><header><b>ORDERS OPS · STORE 0421</b><strong>DEMONSTRATION — NOT FOR SHIPMENT</strong></header><h2>{kind === "pick" ? "Pick ticket" : kind === "labels" ? "Staging labels" : "Shipment manifest"}</h2><p>Order #{order.id} · Shipment {order.shipmentId}<br/>{order.customer} · {order.channel}<br/>Due: {order.promised}</p>{kind === "labels" ? <div className="print-labels">{order.groups.map((group, index) => <section key={group.id}><small>Group {index + 1} of {order.groups.length} · Order #{order.id}</small><h3>{group.location || "LOCATION NOT ASSIGNED"}</h3><b>{group.label}</b><ul>{group.itemIds.map(id => { const item = order.items.find(value => value.id === id); return <li key={id}>{item?.quantity} × {item?.name} · #{item?.sku}</li>; })}</ul><p>Staged by {group.stagedBy || "Not staged"}</p></section>)}</div> : <table><thead><tr><th>Item / model</th><th>Description</th><th>Needed</th><th>Picked</th><th>{kind === "pick" ? "Pick location" : "Staging location"}</th></tr></thead><tbody>{[...order.items].sort((a, b) => a.routeRank - b.routeRank).map(item => <tr key={item.id}><td>#{item.sku}<small>{item.model}</small></td><td>{item.name}</td><td>{item.quantity}</td><td>{item.pickedQuantity}</td><td>{kind === "pick" ? item.verifiedLocation || item.location : order.groups.filter(group => group.itemIds.includes(item.id)).map(group => group.location || "Not staged").join(" + ")}</td></tr>)}</tbody></table>}<footer>Fictional demonstration data · Confirm all items and locations in the approved system of record.</footer></article>}</div>;
}
